# Generated by Django 5.0.6 on 2024-07-03 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0002_user_created_at_user_status_user_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
